### ISSUE TITLE
Installation instruction discrepancy 

### ISSUE THREAD

**Issue by lettucegoblin** [captainzero93/sd-webui-bubble-prompter#1]
This is hardcoded to `extensions\bubble_prompter` 
https://github.com/captainzero93/sd-webui-bubble-prompter/blob/a04a993f71d5aebd9d365e55ebfd1c405edd577d/scripts/bubble_prompter.py#L124

but the readme instructions will make the folder `extensions\sd-webui-bubble-prompter`
https://github.com/captainzero93/sd-webui-bubble-prompter/blob/a04a993f71d5aebd9d365e55ebfd1c405edd577d/README.md?plain=1#L16

I see two options:
1. change the code to  `file_path = os.path.join(scripts.basedir(), "extensions", "sd-webui-bubble-prompter", file_name) `
2. readme changed to `git clone https://github.com/captainzero93/sd-webui-bubble-prompter.git bubble-prompter`

I think #2 might cause issues with installing it in whatever frontend extension manager.

Btw, thank you for making this available!

**Comment by captainzero93** [comment]
thank you , changed the readme, if any errors are caused I'll edit the code
